### ISSUE TITLE
This extension is gone

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [thdoan/autofill-firefox#6]
Today I saw this extension is gone on addons.mozilla.org. Can you upload a new version?
As my suggestion, you can port your Chrome extension to update, just need few works to do.
See: https://addons.mozilla.org/developers/

**Comment by thdoan** [comment]
This has been replaced with Autofill Quantum: https://addons.mozilla.org/firefox/addon/autofill-quantum/
