### ISSUE TITLE
Port to Pale Moon

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [thdoan/autofill-firefox#7]
Do you want to port this extension to Pale Moon?

**Comment by thdoan** [comment]
There are no plans to support Pale Moon. This project is based on UXP, so you can try to manually load it in Pale Moon, but beware that it's way outdated compared to Autofill for Chrome / Firefox Quantum.

Something to check out:
https://forum.palemoon.org/viewtopic.php?t=21214
